name: My Workflow
on:
  push:
    branches:
      - 'releases/*'
jobs:
  My Workflow:
    name: RETRIEVE CODE
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
