name: Extract branch name
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Extract branch name
       shell: bash
       run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
     - name: Test
       run: echo "${BRANCH_NAME}"
    
