name: TESTING-BRANCH
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: TESTING-BRANCH
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
